#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Wired 802.1X Authentication
LUCI_DEPENDS:=+w8021x

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
